# Generated by Django 3.2.6 on 2021-08-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '文件类型',
                'verbose_name_plural': '文件类型',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '级别',
                'verbose_name_plural': '级别',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '类别主题',
                'verbose_name_plural': '类别主题',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('presenter', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('visits', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('recommended_tag', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('comment_scoring', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('file_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.filecategory')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.grade')),
                ('topic_categroy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.topiccategory')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
                'ordering': ('-upload_date', '-comment_scoring'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('nickname', models.CharField(max_length=200)),
                ('is_audit', models.BooleanField(default=False)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('scoring', models.IntegerField(choices=[(1, '一分'), (2, '两分'), (3, '三分'), (4, '四分'), (5, '五分')], default=1)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqmu.fileupload')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ('-comment_date',),
            },
        ),
    ]
