# Generated by Django 3.2.6 on 2021-08-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0003_auto_20210811_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='release_date',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
    ]
