# Generated by Django 3.2.6 on 2021-08-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0004_alter_fileupload_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='form',
            field=models.IntegerField(choices=[(1, '文件或者链接'), (2, '图片'), (3, '音频'), (4, '视频')], default=1, verbose_name='展现形式'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqmu.fileupload', verbose_name='文件名'),
        ),
    ]
