# Generated by Django 3.2.6 on 2021-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0005_auto_20210813_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='scoring',
            field=models.IntegerField(choices=[(1, '一分'), (2, '两分'), (3, '三分'), (4, '四分'), (5, '五分')], default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.TextField(verbose_name='文件描述'),
        ),
    ]
