# Generated by Django 3.2.6 on 2021-08-14 07:05

import cqmu.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0007_auto_20210813_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='', help_text='可以将上传后的文件URL复制到下方URL字段中', max_length=200, storage=cqmu.storage.CosStorage(), upload_to='', verbose_name='文件'),
            preserve_default=False,
        ),
    ]
