# Generated by Django 3.2.6 on 2021-08-14 07:59

import cqmu.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0008_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, help_text='文件大小不超过30MB', max_length=200, null=True, storage=cqmu.storage.CosStorage(), upload_to='', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='url',
            field=models.URLField(blank=True, help_text='文件类型的展现形式为超链接，本字段必填', null=True, verbose_name='URL'),
        ),
    ]
