# Generated by Django 3.2.6 on 2021-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0009_auto_20210814_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='form',
            field=models.IntegerField(choices=[(1, '超链接'), (2, '文件[doc|docx|ppt|pptx|pdf]-下载按钮'), (3, '图片[jpg|jpeg|png|bmp]-下载按钮'), (4, '音频[mp3]-下载按钮'), (5, '视频[mp4]-下载按钮')], default=1, verbose_name='展现形式'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='release_date',
            field=models.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='上传日期'),
        ),
    ]
