# Generated by Django 3.2.6 on 2021-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0010_auto_20210815_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='icon',
            field=models.URLField(default='', verbose_name='文件类型展示图片'),
            preserve_default=False,
        ),
    ]
