# Generated by Django 3.2.6 on 2021-08-16 14:31

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0011_filecategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=simplepro.components.fields.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_upload',
            field=simplepro.components.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqmu.fileupload', verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_audit',
            field=simplepro.components.fields.SwitchField(default=False, verbose_name='是否审核'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='label',
            field=simplepro.components.fields.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='scoring',
            field=simplepro.components.fields.IntegerField(choices=[(1, '一分'), (2, '两分'), (3, '三分'), (4, '四分'), (5, '五分')], default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='form',
            field=simplepro.components.fields.IntegerField(choices=[(1, '超链接'), (2, '文件[doc|docx|ppt|pptx|pdf]-下载按钮'), (3, '图片[jpg|jpeg|png|bmp]-下载按钮'), (4, '音频[mp3]-下载按钮'), (5, '视频[mp4]-下载按钮')], default=1, verbose_name='展现形式'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='seq',
            field=simplepro.components.fields.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='author',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='data_source',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='文件描述'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_category',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.filecategory', verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='grade',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.grade', verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='presenter',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='recommended_tag',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='release_date',
            field=simplepro.components.fields.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='topic_category',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.topiccategory', verbose_name='类别主题'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='seq',
            field=simplepro.components.fields.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='seq',
            field=simplepro.components.fields.IntegerField(default=0, verbose_name='排序序号'),
        ),
    ]
