# Generated by Django 3.2.6 on 2021-09-28 09:54

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0012_auto_20210816_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ('-upload_date', '-comment_scoring', '-id'), 'verbose_name': '文件上传', 'verbose_name_plural': '文件上传'},
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='parent',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cqmu.topiccategory', verbose_name='上级分类'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=simplepro.components.fields.DateTimeField(auto_now_add=True, verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='label',
            field=simplepro.components.fields.CharField(blank=True, max_length=200, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='author',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='data_source',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='presenter',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='主讲人'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='recommended_tag',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='推荐标签'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='label',
            field=simplepro.components.fields.CharField(max_length=200, verbose_name='类别主题'),
        ),
    ]
