# Generated by Django 3.2.6 on 2022-01-18 23:05

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0016_auto_20220114_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='is_open',
            field=simplepro.components.fields.SwitchField(default=False, verbose_name='是否开放'),
        ),
    ]
