# Generated by Django 3.2.6 on 2022-02-09 15:12

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0017_homebanner_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'ordering': ('seq',), 'permissions': [('open_admin_site', 'Can enter the admin site')], 'verbose_name': '类别主题', 'verbose_name_plural': '类别主题'},
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='is_open',
            field=simplepro.components.fields.SwitchField(default=False, verbose_name='是否显示'),
        ),
    ]
