# Generated by Django 3.2.6 on 2022-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0018_auto_20220209_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='small_size',
            field=models.ImageField(upload_to='banner/', verbose_name='主题图片-小尺寸'),
        ),
    ]
