# Generated by Django 3.2.6 on 2022-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0019_alter_banner_small_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='big_size',
            field=models.ImageField(upload_to='banner/', verbose_name='主题图片-大尺寸'),
        ),
    ]
