# Generated by Django 3.2.6 on 2022-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0020_alter_banner_big_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecategory',
            name='icon',
            field=models.ImageField(upload_to='file_category/', verbose_name='文件类型展示图片'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='big_size',
            field=models.ImageField(upload_to='home_banner/', verbose_name='首页图片'),
        ),
    ]
