# Generated by Django 3.2.6 on 2022-03-08 11:28

import cqmu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqmu', '0021_auto_20220307_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='big_size',
            field=models.ImageField(help_text='图片大小不超过 8 MB', upload_to='banner/', validators=[cqmu.models.validate_image], verbose_name='主题图片-大尺寸'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='small_size',
            field=models.ImageField(help_text='图片大小不超过 8 MB', upload_to='banner/', validators=[cqmu.models.validate_image], verbose_name='主题图片-小尺寸'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='icon',
            field=models.ImageField(help_text='图片大小不超过 8 MB', upload_to='file_category/', validators=[cqmu.models.validate_image], verbose_name='文件类型展示图片'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, help_text='文件大小不超过 256 MB', max_length=200, null=True, upload_to='file/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='big_size',
            field=models.ImageField(help_text='图片大小不超过 8 MB', upload_to='home_banner/', validators=[cqmu.models.validate_image], verbose_name='首页图片'),
        ),
    ]
